name: Release
on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup config
        run: |
          git config --global user.name "Net9 Oy"
          git config --global user.email "admin@net9.fi"
      - name: Install deps
        run: |
          sudo apt-get install -y git-buildpackage debhelper
      - name: Generate changelog
        run: |
          DEBEMAIL=admin@net9.fi gbp dch --release --full --id-length=7 --spawn-editor=never --git-author --dch-opt='-U' --distribution experimental
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update changelog"
          commit_options: "--no-verify --signoff"
      - name: Tag release
        run: |
          gbp tag
          git push --tags
          echo "TAG=$(git describe --tags)" >> $GITHUB_ENV
      - name: Build release
        run: |
          make deb
          echo "DEB_PATH=$(ls ../*.deb)" >> $GITHUB_ENV
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.DEB_PATH }}
          tag: ${{ env.TAG }}
          overwrite: true